<a href="https://colab.research.google.com/github/shishiradk/NLP-pratices/blob/main/sms_spam_ham.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [119]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection',sep='\t',names=["label","message"])

In [120]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [121]:
#data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [122]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [123]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word)for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [124]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

Create a Bag of Words

In [125]:
#output feature
y=pd.get_dummies(messages['label'])
y.iloc[:,0].values

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [126]:
y=y.iloc[:,0].values

In [127]:
y.shape

(5572,)

In [128]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [129]:
#create the bag of words model
from sklearn.feature_extraction.text import CountVectorizer
#for binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [130]:
len(X_train),len(y_train)

(4457, 4457)

In [131]:
#independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [132]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))


In [133]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [134]:
cv.vocabulary_

{'alright': np.int64(52),
 'omw': np.int64(1493),
 'gotta': np.int64(852),
 'chang': np.int64(325),
 'order': np.int64(1518),
 'half': np.int64(897),
 'th': np.int64(2106),
 'work': np.int64(2439),
 'tri': np.int64(2189),
 'contact': np.int64(414),
 'last': np.int64(1102),
 'weekend': np.int64(2378),
 'draw': np.int64(561),
 'show': np.int64(1878),
 'prize': np.int64(1651),
 'guarante': np.int64(877),
 'call': np.int64(247),
 'claim': np.int64(351),
 'code': np.int64(370),
 'valid': np.int64(2292),
 'hr': np.int64(977),
 'ppm': np.int64(1632),
 'tri contact': np.int64(2190),
 'contact last': np.int64(418),
 'last weekend': np.int64(1105),
 'weekend draw': np.int64(2379),
 'draw show': np.int64(563),
 'show prize': np.int64(1880),
 'prize guarante': np.int64(1654),
 'guarante call': np.int64(878),
 'call claim': np.int64(252),
 'claim code': np.int64(353),
 'code valid': np.int64(373),
 'valid hr': np.int64(2293),
 'hr ppm': np.int64(978),
 'home': np.int64(953),
 'dad': np.int64(477),


In [135]:
from sklearn.naive_bayes import MultinomialNB


In [136]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [137]:
y_pred=spam_detect_model.predict(X_test)

In [138]:
from sklearn.metrics import accuracy_score,classification_report

In [139]:
accuracy_score(y_test,y_pred)

0.9874439461883409

In [140]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.95      0.95      0.95       141
        True       0.99      0.99      0.99       974

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



create the TF-IDF model

In [141]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [142]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [143]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.255, 0.39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.364, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0,

In [144]:
tv.vocabulary_

{'haha': np.int64(897),
 'hope': np.int64(966),
 'hear': np.int64(921),
 'receipt': np.int64(1723),
 'sound': np.int64(1959),
 'gd': np.int64(783),
 'luck': np.int64(1228),
 'sorri': np.int64(1953),
 'miss': np.int64(1326),
 'babe': np.int64(134),
 'late': np.int64(1114),
 'slept': np.int64(1914),
 'enjoy': np.int64(618),
 'drive': np.int64(577),
 'lesson': np.int64(1149),
 'boytoy': np.int64(218),
 'teas': np.int64(2088),
 'kiss': np.int64(1091),
 'sorri miss': np.int64(1957),
 'miss babe': np.int64(1328),
 'hope enjoy': np.int64(967),
 'teas kiss': np.int64(2089),
 'parti': np.int64(1548),
 'place': np.int64(1605),
 'usf': np.int64(2294),
 'charg': np.int64(330),
 'way': np.int64(2357),
 'appreci': np.int64(87),
 'yeah': np.int64(2477),
 'got': np.int64(849),
 'room': np.int64(1783),
 'one': np.int64(1495),
 'yeah got': np.int64(2478),
 'ye': np.int64(2475),
 'last': np.int64(1109),
 'week': np.int64(2370),
 'take': np.int64(2071),
 'live': np.int64(1177),
 'call': np.int64(250),
 'l

In [145]:
#output features
y=pd.get_dummies(messages['label'])

In [146]:
y=y.iloc[:,0].values

In [147]:
y.shape

(5572,)

In [148]:
from sklearn.naive_bayes import MultinomialNB

In [149]:
spam_tfidf_model = MultinomialNB().fit(X_train,y_train)

In [150]:
y_pred=spam_tfidf_model.predict(X_test)

In [151]:
accuracy_score(y_test,y_pred)
print(score)

0.9775784753363229


In [152]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       1.00      0.82      0.90       151
        True       0.97      1.00      0.99       964

    accuracy                           0.98      1115
   macro avg       0.99      0.91      0.94      1115
weighted avg       0.98      0.98      0.97      1115

